@echo off
rem ============================================================
rem FuXuan installer component - OpenClaw Gateway
rem The pinned OpenClaw package is bundled under bridge\node_modules.
rem This component initializes the user's OpenClaw profile, installs the
rem Gateway scheduled task, starts it, and waits for port 18789.
rem Usage: install-openclaw.cmd [/CHECK]
rem ============================================================
setlocal EnableExtensions EnableDelayedExpansion
set "APP=%~dp0..\.."
set "CHECK=0"
if /I "%~1"=="/CHECK" set "CHECK=1"
set "LOG=%TEMP%\fuxuan-openclaw-install.log"
set "NODE=%APP%\bridge\node\node.exe"
set "CLI=%APP%\bridge\node_modules\openclaw\openclaw.mjs"
set "CFG=%USERPROFILE%\.openclaw\openclaw.json"

if not exist "%NODE%" set "NODE=node"

if "%CHECK%"=="1" (
    if exist "%CLI%" (echo [CHECK] OpenClaw package: PRESENT) else (echo [CHECK] OpenClaw package: MISSING)
    netstat -ano | findstr /R /C:":18789 .*LISTENING" >nul 2>&1
    if errorlevel 1 (echo [CHECK] OpenClaw Gateway: NOT RUNNING) else (echo [CHECK] OpenClaw Gateway: RUNNING)
    if exist "%CFG%" (echo [CHECK] OpenClaw config: PRESENT) else (echo [CHECK] OpenClaw config: MISSING)
    exit /b 0
)

if not exist "%CLI%" (
    echo [ERROR] OpenClaw package is missing from the installer.
    echo [ERROR] Rebuild the installer with the bundled OpenClaw package.
    exit /b 20
)

>"%LOG%" echo FuXuan OpenClaw setup started %DATE% %TIME%
>>"%LOG%" echo [INFO] user=%USERNAME% profile=%USERPROFILE%
>>"%LOG%" echo [INFO] node=%NODE%
>>"%LOG%" echo [INFO] cli=%CLI%
echo [INFO] OpenClaw is bundled; no separate npm installation is required.

rem The installer writes this token before component scripts run. Recover it
rem from HKCU as well because an elevated installer process may have stale env.
if not defined OPENCLAW_GATEWAY_TOKEN for /f "tokens=2*" %%A in ('reg query "HKCU\Environment" /v OPENCLAW_GATEWAY_TOKEN 2^>nul ^| findstr /I "OPENCLAW_GATEWAY_TOKEN"') do set "OPENCLAW_GATEWAY_TOKEN=%%B"
if not defined OPENCLAW_GATEWAY_TOKEN if defined BRIDGE_TOKEN set "OPENCLAW_GATEWAY_TOKEN=%BRIDGE_TOKEN%"
if not defined OPENCLAW_GATEWAY_TOKEN (
    >>"%LOG%" echo [ERROR] OPENCLAW_GATEWAY_TOKEN is missing from process and HKCU environment.
    echo [ERROR] Gateway token was not generated by the installer.
    echo [ERROR] Please rerun the installer instead of starting the bridge manually.
    exit /b 21
)
>>"%LOG%" echo [INFO] gateway token is present (value omitted).
if not defined DEEPSEEK_API_KEY for /f "tokens=2*" %%A in ('reg query "HKCU\Environment" /v DEEPSEEK_API_KEY 2^>nul ^| findstr /I "DEEPSEEK_API_KEY"') do set "DEEPSEEK_API_KEY=%%B"

rem Create a non-interactive local profile on first install. Existing profiles
rem are respected and only the local Gateway service is started.
if not exist "%CFG%" (
    >>"%LOG%" echo [INFO] initializing config: %CFG%
    echo [INFO] Initializing OpenClaw local Gateway profile...
    "%NODE%" "%CLI%" onboard --non-interactive --accept-risk --mode local --gateway-bind loopback --gateway-port 18789 --gateway-auth token --gateway-token-ref-env OPENCLAW_GATEWAY_TOKEN --auth-choice skip --skip-channels --skip-search --skip-skills --skip-hooks --skip-ui --skip-bootstrap --skip-health --install-daemon --suppress-gateway-token-output >>"%LOG%" 2>&1
    >>"%LOG%" echo [INFO] onboard exit=%ERRORLEVEL%
    if errorlevel 1 (
        echo [ERROR] OpenClaw initialization failed. See "%LOG%".
        exit /b 22
    )
)

rem Configure the optional cloud provider without writing the API key into
rem openclaw.json. The Gateway resolves it from the user's environment.
if defined DEEPSEEK_API_KEY (
    >>"%LOG%" echo [INFO] applying DeepSeek provider configuration.
    set "PATCH=%TEMP%\fuxuan-openclaw-models.json5"
    >"!PATCH!" echo {
    >>"!PATCH!" echo   models: {
    >>"!PATCH!" echo     providers: {
    >>"!PATCH!" echo       deepseek: {
    >>"!PATCH!" echo         baseUrl: "https://api.deepseek.com/v1",
    >>"!PATCH!" echo         api: "openai-completions",
    >>"!PATCH!" echo         apiKey: { source: "env", provider: "default", id: "DEEPSEEK_API_KEY" },
    >>"!PATCH!" echo         models: [{ id: "deepseek-chat", name: "DeepSeek Chat", reasoning: true }]
    >>"!PATCH!" echo       }
    >>"!PATCH!" echo     }
    >>"!PATCH!" echo   },
    >>"!PATCH!" echo   agents: { defaults: { model: { primary: "deepseek/deepseek-chat" }, utilityModel: "deepseek/deepseek-chat" } }
    >>"!PATCH!" echo }
    "%NODE%" "%CLI%" config patch --file "!PATCH!" >>"%LOG%" 2>&1
    set "PATCH_RC=!ERRORLEVEL!"
    del /q "!PATCH!" >nul 2>&1
    if not "!PATCH_RC!"=="0" echo [WARN] DeepSeek provider configuration was not applied; local chat still works.
)

echo [INFO] Installing or refreshing the OpenClaw Gateway service...
>>"%LOG%" echo [INFO] gateway install begin.
"%NODE%" "%CLI%" gateway install --force --port 18789 >>"%LOG%" 2>&1
>>"%LOG%" echo [INFO] gateway install exit=%ERRORLEVEL%
if errorlevel 1 (
    echo [ERROR] OpenClaw Gateway service registration failed. See "%LOG%".
    exit /b 23
)
"%NODE%" "%CLI%" gateway start --port 18789 >>"%LOG%" 2>&1
>>"%LOG%" echo [INFO] gateway start exit=%ERRORLEVEL%

echo [INFO] Waiting for OpenClaw Gateway on 127.0.0.1:18789...
for /l %%I in (1,1,30) do (
    netstat -ano | findstr /R /C:":18789 .*LISTENING" >nul 2>&1
    if not errorlevel 1 goto :gateway_ready
    ping -n 2 127.0.0.1 >nul
)
echo [ERROR] OpenClaw Gateway did not become ready within 30 seconds.
echo [ERROR] See "%LOG%" and rerun the Start Menu dependency check.
exit /b 24

:gateway_ready
echo [OK] OpenClaw Gateway is ready on 127.0.0.1:18789.
>>"%LOG%" echo [OK] OpenClaw Gateway is ready on 127.0.0.1:18789.
exit /b 0
