'use strict';
const fs=require('fs'),path=require('path'),zlib=require('zlib');
const DEFAULTS={face:{x:0.25,y:0.05,width:0.5,height:0.42},left_arm:{x:0.05,y:0.3,width:0.35,height:0.5},right_arm:{x:0.6,y:0.3,width:0.35,height:0.5},torso:{x:0.25,y:0.35,width:0.5,height:0.5}};
function validateRegions(regions){const value={...DEFAULTS,...(regions||{})};for(const [name,r] of Object.entries(value)){if(!r||![r.x,r.y,r.width,r.height].every(Number.isFinite)||r.x<0||r.y<0||r.width<=0||r.height<=0||r.x+r.width>1||r.y+r.height>1)throw Error(`invalid ROI rectangle: ${name}`)}return value}
function png(file){const b=fs.readFileSync(file);if(b.length<33||b.subarray(0,8).toString('hex')!=='89504e470d0a1a0a')throw Error(`unsupported PNG signature: ${file}`);let o=8,w=0,h=0,d=0,t=0,interlace=0,ch=[];while(o+12<=b.length){const n=b.readUInt32BE(o),end=o+12+n;if(end>b.length)throw Error(`truncated PNG chunk: ${file}`);const k=b.toString('ascii',o+4,o+8),data=b.subarray(o+8,o+8+n);if(k==='IHDR'){w=data.readUInt32BE(0);h=data.readUInt32BE(4);d=data[8];t=data[9];interlace=data[12]}if(k==='IDAT')ch.push(data);o=end;if(k==='IEND')break}if(!w||!h)throw Error(`invalid PNG dimensions: ${file}`);if(interlace!==0)throw Error(`interlaced PNG unsupported: ${file}`);if(d!==8||(t!==2&&t!==6))throw Error(`unsupported PNG format: ${file}`);const bpp=t===6?4:3,raw=zlib.inflateSync(Buffer.concat(ch)),stride=w*bpp;if(raw.length!==h*(stride+1))throw Error(`PNG decompressed length mismatch: ${file}`);const pix=Buffer.alloc(stride*h);let s=0;for(let y=0;y<h;y++){const f=raw[s++],row=y*stride;for(let x=0;x<stride;x++){const v=raw[s++],l=x>=bpp?pix[row+x-bpp]:0,u=y?pix[row-stride+x]:0,ul=y&&x>=bpp?pix[row-stride+x-bpp]:0;if(f===0)pix[row+x]=v;else if(f===1)pix[row+x]=(v+l)&255;else if(f===2)pix[row+x]=(v+u)&255;else if(f===3)pix[row+x]=(v+Math.floor((l+u)/2))&255;else if(f===4){const p=l+u-ul,pa=Math.abs(p-l),pb=Math.abs(p-u),pc=Math.abs(p-ul);pix[row+x]=(v+(pa<=pb&&pa<=pc?l:pb<=pc?u:ul))&255}else throw Error(`invalid PNG filter ${f}: ${file}`)}}if(t===2){const rgba=Buffer.alloc(w*h*4);for(let i=0,j=0;i<pix.length;i+=3,j+=4){rgba[j]=pix[i];rgba[j+1]=pix[i+1];rgba[j+2]=pix[i+2];rgba[j+3]=255}return {width:w,height:h,pixels:rgba}}return {width:w,height:h,pixels:pix}}
function metric(a,b,r){if(a.width!==b.width||a.height!==b.height)throw Error('ROI frame dimensions mismatch');const x0=Math.floor(r.x*a.width),y0=Math.floor(r.y*a.height),x1=Math.min(a.width,Math.ceil((r.x+r.width)*a.width)),y1=Math.min(a.height,Math.ceil((r.y+r.height)*a.height));let n=0,delta=0,model=0;for(let y=y0;y<y1;y++)for(let x=x0;x<x1;x++){const i=(y*a.width+x)*4,j=(y*b.width+x)*4;n++;const ai=a.pixels[i]+a.pixels[i+1]+a.pixels[i+2],bi=b.pixels[j]+b.pixels[j+1]+b.pixels[j+2];if(ai>72||bi>72)model++;delta+=Math.abs(a.pixels[i]-b.pixels[j])+Math.abs(a.pixels[i+1]-b.pixels[j+1])+Math.abs(a.pixels[i+2]-b.pixels[j+2])}return {relativeToBaseline:+(delta/Math.max(1,n*3)).toFixed(4),fromToDelta:+(delta/Math.max(1,n*3)).toFixed(4),modelPixelRatio:+(model/Math.max(1,n)).toFixed(6),coverage:+(model/Math.max(1,n)).toFixed(6),pixelCount:n,adjacentDifference:null}}
function analyzeRoiFrames(frames,regions){const rs=validateRegions(regions);if(!Array.isArray(frames)||frames.length<2)throw Error('ROI analysis needs at least two explicit frames');const loaded=frames.map((f,i)=>{if(!f||typeof f.path!=='string'||!fs.existsSync(f.path))throw Error(`ROI frame missing at index ${i}: ${f?.path}`);return {...f,image:png(f.path)}});const base=loaded[0].image,out={};for(const [name,r] of Object.entries(rs)){const rows=loaded.slice(1).map((f,i)=>{const m=metric(base,f.image,r),adj=metric(loaded[i].image,f.image,r);return {runId:f.runId||null,stage:f.stage||null,from:path.basename(loaded[i].path),to:path.basename(f.path),relativeToBaseline:m.relativeToBaseline,fromToDelta:adj.relativeToBaseline,adjacentDifference:adj.relativeToBaseline,coverage:m.coverage}});out[name]={roi:r,peakRgbMeanDelta:Math.max(...rows.map(x=>x.relativeToBaseline)),adjacentPeak:Math.max(...rows.map(x=>x.adjacentDifference)),resetStable:null,resetEvaluation:'notEvaluated',coverage:Math.max(...rows.map(x=>x.coverage)),status:'EvidenceOnly',frames:rows}}return out}
function analyzeRoiDirectory(dir,regions){const files=fs.readdirSync(dir).filter(x=>x.toLowerCase().endsWith('.png')).sort();return analyzeRoiFrames(files.map(f=>({path:path.join(dir,f)})),regions)}
function pickResetStage(stages){return stages.filter(x=>/^reset$/i.test(String(x.stage||''))).slice(-1)[0]||null}
function analyzeRoiPhases(phases,regions){const rs=validateRegions(regions);if(!Array.isArray(phases)||phases.length<2)throw Error('ROI phases need at least two stages');const loaded=phases.map(stage=>{if(!stage||!Array.isArray(stage.files)||!stage.files.length)throw Error(`ROI phase has no files: ${stage?.stage||'unknown'}`);return {stage:stage.stage||'unknown',frames:stage.files.map(file=>({file,path:file,frame:png(file)}))}});const base=loaded[0].frames[0].frame,out={};for(const [name,r] of Object.entries(rs)){const stages=loaded.map(stage=>({stage:stage.stage,peakRgbMeanDelta:Math.max(...stage.frames.map(item=>metric(base,item.frame,r).relativeToBaseline)),frames:stage.frames.map(item=>({file:path.basename(item.path),...metric(base,item.frame,r)}))}));const reset=pickResetStage(stages),returnStage=stages.find(x=>/^reset_hand$/i.test(x.stage));const resetHandFinalDelta=returnStage?returnStage.frames[returnStage.frames.length-1].relativeToBaseline:null;out[name]={roi:r,stages,resetHandFinalDelta,resetStable:reset&&returnStage?reset.peakRgbMeanDelta<=0.1&&resetHandFinalDelta<=0.1:null,resetEvaluation:reset&&returnStage?'evaluated':'notEvaluated',status:'EvidenceOnly'}}return out}
module.exports={DEFAULTS,validateRegions,analyzeRoiDirectory,analyzeRoiFrames,analyzeRoiPhases,pickResetStage};
