'use strict';
const fs=require('fs'),os=require('os'),path=require('path'),{once}=require('events'),{spawn}=require('child_process');
const exe=process.argv[2];if(!exe||!fs.existsSync(exe))throw Error('missing DesktopPet.exe');
const root=fs.mkdtempSync(path.join(os.tmpdir(),'fuxuan_walk_boundary_')),inbox=path.join(root,'inbox.txt'),logFile=path.join(root,'logs','player_log.txt');
const sleep=ms=>new Promise(r=>setTimeout(r,ms)),log=()=>{try{return fs.readFileSync(logFile,'utf8')}catch{return''}};
async function wait(marker,offset=0,timeout=30000){const end=Date.now()+timeout;while(Date.now()<end){const s=log().slice(offset);if(s.includes(marker))return s;await sleep(80)}throw Error('timeout: '+marker)}
function lines(){return log().split(/\r?\n/).filter(Boolean)}
function hasLeaseEvent(text){return lines().some(line=>line.includes(text))}
async function send(cmd,marker,timeout=15000){const at=log().length;fs.writeFileSync(inbox,cmd,'utf8');try{return marker?await wait(marker,at,timeout):(await sleep(700),log().slice(at))}finally{fs.writeFileSync(inbox,'','utf8')}}
function latest(marker,offset){const lines=log().slice(offset).split(/\r?\n/).filter(x=>x.includes(marker));return lines.at(-1)||''}
function star(text){const m=[...text.matchAll(/\[StarArmState\] star-arm dragging=(True|False)([^\r\n]*)/g)].pop();if(!m)throw Error('star snapshot missing');const out={dragging:m[1]==='True'};for(const p of m[2].trim().split(/\s+/)){const [k,v]=p.split('=');if(k&&v!==undefined)out[k]=Number(v)}return out}
function desktop(text){const m=[...text.matchAll(/\[DesktopState\] version=(\d+) mode=([^ ]+) x=(-?\d+) y=(-?\d+) velocity=\((-?\d+),(-?\d+)\) onGround=(True|False) dragging=(True|False) paused=(True|False)/g)].pop();return m?{version:+m[1],mode:m[2],x:+m[3],y:+m[4],vx:+m[5],vy:+m[6],onGround:m[7]==='True',dragging:m[8]==='True',paused:m[9]==='True'}:null}
(async()=>{fs.writeFileSync(path.join(root,'.test_mode'),'');fs.writeFileSync(inbox,'');const p=spawn(exe,[],{env:{...process.env,FU_XUAN_DATA:root},stdio:'ignore'});let ok=false;try{
 await wait('[DesktopPet] 落地',0,90000);await send('@@sim:idle-actions:off');await send('@@sim:walk:stop');await send('@@sim:expression:stop');await sleep(1000);
 let walkAt=log().length;await send('@@sim:walk:right','已强制开始向右走');await wait('Accepted Walking/walk-pose/walking-state',walkAt,12000);
 let dragAt=log().length;const drag=await send('@@sim:drag:offset:120,0,12','拖动已启动',15000);await wait('Released DragResponse/drag-response/drag-response',dragAt,15000);const dragLog=log().slice(dragAt);
 if(!hasLeaseEvent('Accepted Walking/walk-pose/walking-state'))throw Error('walking lease was not reacquired after drag release');await send('@@sim:desktop-state','[DesktopState]');const afterDrag=desktop(log());
 const pauseAt=log().length;await send('@@sim:pause:2','pause accepted',12000);await send('@@sim:desktop-state','[DesktopState]');const paused=desktop(log().slice(pauseAt));await sleep(700);await send('@@sim:star-arm-state','[StarArmState]');const pausedPose=star(log().slice(pauseAt));const pauseLog=log().slice(pauseAt);
 const resumeAt=log().length;await send('@@sim:resume','resume accepted',12000);if(!hasLeaseEvent('Accepted Walking/walk-pose/walking-state'))throw Error('walking lease was not reacquired after resume');await send('@@sim:desktop-state','[DesktopState]');const resumed=desktop(log().slice(resumeAt));
 await send('@@sim:walk:stop','已强制停止走路');await sleep(5000);const longAt=log().length;await send('@@sim:star-arm-state','[StarArmState]');const longStopped=star(log().slice(longAt));
 const evidence=log().split(/\r?\n/).filter(s=>/Handoff Walking|DragHandoff|Accepted DragResponse|Released DragResponse|Accepted Walking\/walk-pose|Released Walking\/walk-pose|pause accepted|resume accepted|已强制停止走路|\[DesktopState\]|\[StarArmState\]/.test(s));
 ok=true;console.log(JSON.stringify({status:'pass',dragHandoff:{accepted:dragLog.includes('[DragHandoff] walking-to-drag accepted'),dragStarted:dragLog.includes('拖动已启动'),dragReleased:dragLog.includes('Released DragResponse/drag-response/drag-response'),walkingReacquired:true,afterDrag},pauseResume:{paused,resumed,pausedPose,pauseReleasedWalking:pauseLog.includes('Released Walking/walk-pose/walking-state'),resumeReacquiredWalking:true},longStop:{fiveSecondSnapshot:longStopped},evidenceLines:evidence}));
}finally{if(p.exitCode===null){try{fs.writeFileSync(inbox,'@@test:quit','utf8')}catch{}await Promise.race([once(p,'exit'),sleep(10000)]);if(p.exitCode===null)try{p.kill()}catch{}}if(!ok)console.error('Preserved isolated root: '+root);else fs.rmSync(root,{recursive:true,force:true})}})().catch(e=>{console.error(e.stack||e);process.exitCode=1});
