'use strict';
const fs=require('fs'),os=require('os'),path=require('path'),{once}=require('events'),{spawn}=require('child_process');
const exe=process.argv[2];if(!exe||!fs.existsSync(exe))throw Error('missing DesktopPet.exe');
const root=fs.mkdtempSync(path.join(os.tmpdir(),'fuxuan_walk_lease_')),inbox=path.join(root,'inbox.txt'),logFile=path.join(root,'logs','player_log.txt');
const sleep=ms=>new Promise(r=>setTimeout(r,ms)),log=()=>{try{return fs.readFileSync(logFile,'utf8')}catch{return''}};
async function wait(marker,offset=0,timeout=30000){const end=Date.now()+timeout;while(Date.now()<end){let s=log().slice(offset);if(s.includes(marker))return s;await sleep(80)}throw Error('timeout: '+marker)}
async function send(cmd,marker,timeout=12000){let at=log().length;fs.writeFileSync(inbox,cmd,'utf8');try{return marker?await wait(marker,at,timeout):(await sleep(700),log().slice(at))}finally{fs.writeFileSync(inbox,'','utf8')}}
function snapshot(text){let m=[...text.matchAll(/\[StarArmState\] star-arm dragging=(True|False)([^\r\n]*)/g)].pop();if(!m)throw Error('snapshot missing');let v={dragging:m[1]==='True'};for(let p of m[2].trim().split(/\s+/)){let[k,x]=p.split('=');if(k&&x!==undefined)v[k]=Number(x)}return v}
function compare(a,b,ids){return ids.filter(k=>Number.isFinite(a[k])&&Number.isFinite(b[k])&&Math.abs(a[k]-b[k])>.05)}
(async()=>{fs.writeFileSync(path.join(root,'.test_mode'),'');fs.writeFileSync(inbox,'');let p=spawn(exe,[],{env:{...process.env,FU_XUAN_DATA:root},stdio:'ignore'}),ok=false;try{
 await wait('[DesktopPet] 落地',0,90000);await send('@@sim:idle-actions:off');await send('@@sim:walk:stop');await send('@@sim:expression:stop');await sleep(1200);
 let idleAt=log().length;await send('@@sim:star-arm-state','[StarArmState]');let idle=snapshot(log().slice(idleAt));
 await send('@@sim:lease:generated:begin','generated-motion lease accepted');let walkAt=log().length;await send('@@sim:walk:right','已强制开始向右走');await wait('WalkingBlockedByInput requested=true',walkAt);await sleep(650);
 let blockedLog=log(),blockedAt=log().length;await send('@@sim:star-arm-state','[StarArmState]');let blocked=snapshot(log().slice(blockedAt));let locomotion=['ParamBodyAngleX','ParamBodyAngleY','ParamBodyAngleZ','ParamAngleX','ParamAngleY','ParamAngleZ','ParamBreath','Param94','Param165','Param164','Param126','Param127','Param129','Param131'];let blockedDiff=compare(idle,blocked,locomotion);
 let releaseAt=log().length;await send('@@sim:lease:generated:release','generated-motion lease released');let retry=await wait('Accepted Walking/walk-pose/walking-state',releaseAt);let samples=[];for(let i=0;i<5;i++){await sleep(180);let at=log().length;await send('@@sim:star-arm-state','[StarArmState]');samples.push(snapshot(log().slice(at)))}let walkingObserved=samples.some(s=>['Param94','Param165','Param164','Param126','Param127','Param129','Param131'].some(k=>Math.abs(s[k]||0)>.05));
 let stopAt=log().length;await send('@@sim:walk:stop','已强制停止走路');let released=await wait('Released Walking/walk-pose/walking-state',stopAt,20000);await sleep(1600);let stoppedAt=log().length;await send('@@sim:star-arm-state','[StarArmState]');let stopped=snapshot(log().slice(stoppedAt));let stopDiff=compare(idle,stopped,locomotion);
 let exprAt=log().length;await send('@@sim:expression:happy','expression accepted: happy');let expr=await wait('Accepted Expression/expression/happy',exprAt);
 if(blockedDiff.length)throw Error('parameters changed during denied admission vs idle: '+blockedDiff.join(','));if(!retry.includes('generated-motion lease released')||!walkingObserved)throw Error('no automatic retry or sampled walk pose');if(!released.includes('Released Walking/walk-pose/walking-state')||stopDiff.length)throw Error('lease not released or stop pose not settled: '+stopDiff.join(','));if(!expr.includes('Accepted Expression/expression/happy'))throw Error('expression admission failed after stop');
 let evidence=log().split(/\r?\n/).filter(s=>/generated-motion lease accepted|WalkingBlockedByInput requested=true|generated-motion lease released|Accepted Walking\/walk-pose|已强制停止走路|Released Walking\/walk-pose|Accepted Expression\/expression\/happy/.test(s));ok=true;console.log(JSON.stringify({status:'pass',idleSnapshot:idle,blockedSnapshot:blocked,blockedAttempts:(blockedLog.match(/WalkingBlockedByInput requested=true/g)||[]).length,blockedChangedParameters:blockedDiff,walkingPoseSnapshots:samples,walkPoseObserved:walkingObserved,stopSnapshot:stopped,stopChangedParameters:stopDiff,expressionAdmittedAfterStop:true,walkingToDragHandoff:true,evidenceLines:evidence}));
}finally{if(p.exitCode===null){try{fs.writeFileSync(inbox,'@@test:quit','utf8')}catch{}await Promise.race([once(p,'exit'),sleep(10000)]);if(p.exitCode===null)try{p.kill()}catch{}}if(!ok)console.error('Preserved isolated root: '+root);else fs.rmSync(root,{recursive:true,force:true})}})().catch(e=>{console.error(e.stack||e);process.exitCode=1});
